# -*- coding: utf-8 -*-
"""NWITGroupProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JxDtt1NNyDlR4-BHx9hyHz4it5GjRhwG
"""

import re
import cv2
import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from bs4 import BeautifulSoup
from google.colab.patches import cv2_imshow
#info by John Elflein


def get_blood_type_distribution():

  url = "https://www.statista.com/statistics/1112664/blood-type-distribution-us/"

  response = requests.get(url)

  soup = BeautifulSoup(response.text, "html.parser")

  text = soup.get_text()


  categories = ['O-positive','A-positive','B-positive','O-negative', 'A-negative', 'AB-positve', 'B-negative', 'AB-negative' ]

  #reads the values from url using data frame
  alues = ['38','34','9','7','6','3','2','1']


  values = [int(x) for x in values]

  plt.barh(categories, values)
  plt.xlabel('Blood Type Distribution')
  plt.ylabel('Categories')
  plt.title('Blood Type Distribution')
  plt.show()

def influence_User_1():
 message_1 = cv2.imread("message_1.png", cv2.IMREAD_COLOR)

 result = cv2.matchTemplate(message_1, message_1, cv2.TM_CCOEFF_NORMED)
 threshold = 0.8

 location = np.where(result >= threshold)
 for pt in zip(*location[::-1]):
  cv2.rectangle(message_1, pt, (pt[0] + 50, pt[1] + 50), (0, 0, 255), 2)

 cv2_imshow(message_1)
 cv2.waitKey(0)
 cv2.destroyAllWindows()

influence_User_1()

print("Donating blood can potnetially save someone's life!")

def my_video_1():
  url = "https://montgomerycollege0-my.sharepoint.com/personal/drobi172_montgomerycollege_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fdrobi172%5Fmontgomerycollege%5Fedu%2FDocuments%2FAttachments%2FUntitled%20%282%29%2Emp4&ct=1743770441335&or=OWA%2DNT%2DMail&cid=0072c905%2D397f%2D8fc6%2Db249%2D8de87d85fede&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ee3976098%2Dd6d7%2D4264%2D98b1%2D5347dcf1dac8"

  print(url)

  print("Please watch this video on the blood drawing process")


def my_video_2():
  url = "https://montgomerycollege0-my.sharepoint.com/personal/drobi172_montgomerycollege_edu/_layouts/15/stream.aspx?id=%2Fpersonal%2Fdrobi172%5Fmontgomerycollege%5Fedu%2FDocuments%2FAttachments%2FUntitled%20%283%29%2Emp4&ct=1743774440485&or=OWA%2DNT%2DMail&cid=cb862585%2Db004%2Db831%2D6882%2D829e881c4cd1&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Edd82d627%2D9388%2D4dae%2Da720%2D2f09a69a5108"

  print(url)

  print("Please watch the second video on the blood drawing process")
def influence_User_2():

  message_2 = cv2.imread("message_2.png", cv2.IMREAD_COLOR)

  result = cv2.matchTemplate(message_2, message_2, cv2.TM_CCOEFF_NORMED)
  threshold = 0.8

  location = np.where(result >= threshold)
  for pt in zip(*location[::-1]):
   cv2.rectangle(message_2, pt, (pt[0] + 50, pt[1] + 50), (0, 0, 255), 2)
  cv2_imshow(message_2)
  cv2.waitKey(0)
  cv2.destroyAllWindows()

influence_User_2()

print("Friendly reminder to keep blood banks full")

def influence_User_3():
  message_3 = cv2.imread("message_3.png", cv2.IMREAD_COLOR)

  result = cv2.matchTemplate(message_3, message_3, cv2.TM_CCOEFF_NORMED)
  threshold = 0.8

  location = np.where(result >= threshold)
  for pt in zip(*location[::-1]):
   cv2.rectangle(message_3, pt, (pt[0] + 50, pt[1] + 50), (0, 0, 255), 2)
  cv2_imshow(message_3)
  cv2.waitKey(0)
  cv2.destroyAllWindows()

influence_User_3()

print("Here are some facts about blood types related to race")

my_video_1()
my_video_2()